apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: halo-private-posts-post-annotation-setting
  labels:
    plugin.halo.run/pluginName: halo-private-posts
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $el: div
      attrs:
        data-hpp-hide-password-slot: "true"
    - $formkit: hidden
      id: hpp-hide-password-config
      name: privateposts.halo.run/hide-password
      delay: 0
